theme: jekyll-theme-minimal
title: AEM Translation Integration
description: Documentation for AEM and BenQ AI Translation integration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
